ALTER TABLE ar_invoices
  ADD COLUMN IF NOT EXISTS currency_code TEXT,
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS total_inr     NUMERIC,
  ADD COLUMN IF NOT EXISTS balance_inr   NUMERIC;
