-- Create BU master table
CREATE TABLE IF NOT EXISTS bu_master (
  bu_name text primary key,
  created_at timestamptz default now()
);
ALTER TABLE bu_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth read bu_master" ON bu_master FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth write bu_master" ON bu_master FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Create collector master table
CREATE TABLE IF NOT EXISTS collector_master (
  collector_name text primary key,
  created_at timestamptz default now()
);
ALTER TABLE collector_master ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth read collector_master" ON collector_master FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth write collector_master" ON collector_master FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Seed BUs (from Customer_Master sheet)
INSERT INTO bu_master (bu_name) VALUES
  ('BAT BU'),('Central'),('ERTM'),('India Ent BU'),('India MM BU'),
  ('India MM North'),('KAM BU'),('MEA BU'),('SEA BU'),('SME BU')
ON CONFLICT DO NOTHING;

-- Seed collectors
INSERT INTO collector_master (collector_name) VALUES
  ('Arathi'),('Central'),('Juliya'),('Nicky'),('Pavan'),('Prithee'),('Salbi')
ON CONFLICT DO NOTHING;

-- Rename role admin -> admin-edit for existing users
UPDATE user_access SET role = 'admin-edit' WHERE role = 'admin' OR role IS NULL;

-- Seed customer master from Customer_Master sheet (712 rows)
INSERT INTO ar_customer_master (customer_name, bu_name, collector_name, updated_at)
VALUES
  ('Godrej Consumer Products Ltd.', 'KAM BU', 'Pavan'),
  ('Glaxosmithkline Asia Private Limited', 'India Ent BU', 'Salbi'),
  ('Wavin Industries Limited', 'India MM BU', 'Salbi'),
  ('Bajaj Electricals Limited', 'India Ent BU', 'Prithee'),
  ('Anheuser Busch InBev India Limited', 'India Ent BU', 'Pavan'),
  ('MGH Logistics Asia PTE Ltd.', 'India Ent BU', 'Salbi'),
  ('VRS Foods Limited', 'India MM BU', 'Salbi'),
  ('E I D Parry India Limited', 'India Ent BU', 'Juliya'),
  ('J K Cement Limited', 'India Ent BU', 'Salbi'),
  ('Caraway Africa Nigeria Limited', 'MEA BU', 'Pavan'),
  ('Orion Nutritionals Private Limited', 'India Ent BU', 'Salbi'),
  ('DS Spiceco Private Limited', 'India MM BU', 'Salbi'),
  ('TGI Distri Limited- (TGI Group)', 'MEA BU', 'Pavan'),
  ('Gits Food Products Private Limited', 'India MM BU', 'Arathi'),
  ('Swastiks Masalas Pickles & Food Products Private Limited', 'India MM BU', 'Juliya'),
  ('DFM Foods Ltd', 'India MM BU', 'Salbi'),
  ('Galderma India Private Limited', 'India Ent BU', 'Juliya'),
  ('Gemini Edibles & Fats India Limited (GEF)', 'India MM BU', 'Pavan'),
  ('Heavenly Secrets Private Limited (Pilgrim)', 'India MM BU', 'Salbi'),
  ('Del Monte Foods Private Limited (Fieldfresh)', 'India Ent BU', 'Juliya'),
  ('Hershey India Private Limited (ISD)', 'India Ent BU', 'Prithee'),
  ('TI Medical Private Limited (Old)', 'India MM BU', 'Salbi'),
  ('Eveready Industries India Ltd', 'India Ent BU', 'Prithee'),
  ('Parle Agro Private Limited', 'SME BU', 'Arathi'),
  ('Hero Cycles Limited', 'India Ent BU', 'Salbi'),
  ('Buy Happy Marketing LLP', 'India MM BU', 'Juliya'),
  ('Allana Consumer Products Private Limited', 'India MM BU', 'Prithee'),
  ('Hygienic Research Institute Private Limited (HRI)', 'India MM BU', 'Prithee'),
  ('USV Private Limited', 'India Ent BU', 'Juliya'),
  ('Drums Food International Private Limited', 'India MM BU', 'Prithee'),
  ('Drools Pet Food Private Limited', 'India MM BU', 'Prithee'),
  ('Parag Milk Foods Limited', 'India MM BU', 'Prithee'),
  ('GRB Dairy Foods Private Limited', 'India MM BU', 'Juliya'),
  ('Keventer Agro Limited', 'India MM BU', 'Juliya'),
  ('Polycab India Limited', 'India Ent BU', 'Prithee'),
  ('Reckitt Benckiser Arabia FZE-HC', 'MEA BU', 'Juliya'),
  ('Motul India Private Limited', 'India Ent BU', 'Prithee'),
  ('Global Dent Aids Private Limited', 'SME BU', 'Arathi'),
  ('Beiersdorf India Private Limited', 'India MM BU', 'Prithee'),
  ('Kores India Limited', 'India MM BU', 'Juliya'),
  ('Limar Enterprises', 'SME BU', 'Arathi'),
  ('JGI Distribution Pvt. Ltd.', 'India MM BU', 'Salbi'),
  ('Piramal Pharma Limited', 'India Ent BU', 'Prithee'),
  ('Group SNS LLC FZ', 'MEA BU', 'Pavan'),
  ('PT. Santosa Utama Lestari', 'SEA BU', 'Juliya'),
  ('PT Philips Indonesia Commercial', 'SEA BU', 'Juliya'),
  ('Livpure Private Limited', 'India Ent BU', 'Salbi'),
  ('Godrej Tyson Foods Limited', 'KAM BU', 'Pavan'),
  ('Firefox Bikes Private Limited', 'India Ent BU', 'Salbi'),
  ('CG Foods (Nepal) Pvt. Ltd.', 'India Ent BU', 'Salbi'),
  ('Megha Fruit Processing Private Limited', 'India MM BU', 'Juliya'),
  ('Unibic Foods India Pvt Ltd', 'India MM BU', 'Juliya'),
  ('Pureplay Skin Sciences (India) Private Limited', 'India MM BU', 'Prithee'),
  ('Zed Lifestyle Private Limited', 'India Ent BU', 'Prithee'),
  ('Vibhava Marketing Corporation', 'India MM BU', 'Juliya'),
  ('Khoday India Limited', 'SME BU', 'Arathi'),
  ('VIP Industries Limited', 'India Ent BU', 'Prithee'),
  ('HR Food Processing Private Limited', 'India MM BU', 'Salbi'),
  ('Walko Food Company Private Limited', 'India MM BU', 'Juliya'),
  ('Freudenberg Gala Household Products Private Limited', 'India MM BU', 'Prithee'),
  ('Wonderchef Home Appliances Private Limited', 'India MM BU', 'Prithee'),
  ('Kwick Living (I) Private Limited', 'SME BU', 'Arathi'),
  ('Shingar Cosmetics Private Limited', 'SME BU', 'Arathi'),
  ('Marino Food Products Private Limited', 'India MM BU', 'Pavan'),
  ('Sesa Care Private Limited', 'India MM BU', 'Prithee'),
  ('APIS India Limited', 'India MM BU', 'Juliya'),
  ('Herbal Strategi Homecare Private Limited', 'ERTM', 'Arathi'),
  ('Elite Natural Private Limited', 'SME BU', 'Arathi'),
  ('Teamlease Services Limited', 'India Ent BU', 'Pavan'),
  ('Indira Food Private Limited', 'SME BU', 'Arathi'),
  ('Reckitt Benckiser (Bangladesh) Ltd', 'MEA BU', 'Salbi'),
  ('Keya Foods International Private Limited', 'SME BU', 'Arathi'),
  ('Mrs. Bectors Food Specialities Limited (EO Sales)', 'India Ent BU', 'Salbi'),
  ('Karkhana Zinda Tilismath', 'SME BU', 'Arathi'),
  ('Akshayakalpa Farms And Foods Private Limited', 'India MM BU', 'Pavan'),
  ('Springwel Mattresses Private Limited', 'SME BU', 'Arathi'),
  ('Jovees Herbal Care Private Limited', 'India MM BU', 'Juliya'),
  ('Mankind Prime Labs Private Limited', 'India Ent BU', 'Salbi'),
  ('Safa Al Jazeera General Trading Co.', 'SME BU', 'Arathi'),
  ('EPICU Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Adinath Agro Processed Foods Private Limited', 'SME BU', 'Arathi'),
  ('Sriveda Sattva Private Limited', 'SME BU', 'Arathi'),
  ('KRBL Limited', 'India MM BU', 'Salbi'),
  ('Lifelong Online Retail Private Limited', 'SME BU', 'Arathi'),
  ('Mother Dairy Fruit & Vegetable Private Limited', 'India Ent BU', 'Salbi'),
  ('Kansai Nerolac Paints Limited', 'India Ent BU', 'Prithee'),
  ('Gold Crown Beverages (Kenya) Ltd', 'MEA BU', 'Pavan'),
  ('Pipit Sips N Eats LLP', 'SME BU', 'Arathi'),
  ('Bikanervala Foods Private Limited', 'India MM BU', 'Salbi'),
  ('Shree Ganesh Bakery Nandani Private Limited', 'India MM BU', 'Prithee'),
  ('Empire Spices and Foods Limited', 'India MM BU', 'Prithee'),
  ('CG Brewery Nepal Limited', 'India Ent BU', 'Salbi'),
  ('Inbrew Beverages Private Limited (Molson)', 'India MM BU', 'Juliya'),
  ('Desai Foods Private Limited', 'India MM BU', 'Juliya'),
  ('Leake Tesfay Import', 'SME BU', 'Arathi'),
  ('Stove Kraft Limited', 'India MM BU', 'Juliya'),
  ('Sellpro Commerce Private Limited', 'SME BU', 'Arathi'),
  ('Ramdev Food Products Private Limited', 'India MM BU', 'Prithee'),
  ('A V Thomas & Company Limited', 'India MM BU', 'Juliya'),
  ('J L Morison India Limited', 'India Ent BU', 'Prithee'),
  ('Ravi Foods Private Limited', 'India MM BU', 'Pavan'),
  ('Lactalis Trading Malaysia Sdn Bhd', 'SEA BU', 'Pavan'),
  ('Servosonic Lifestyle Private Limited', 'SME BU', 'Arathi'),
  ('Pon Pure Chemical India Private Limited', 'SME BU', 'Arathi'),
  ('Innovative Foods Limited', 'SME BU', 'Arathi'),
  ('PT. Inovasi Pangan Nusantara', 'SEA BU', 'Juliya'),
  ('Nandan Petrochem Ltd', 'India MM BU', 'Prithee'),
  ('S.G. Nepal Pvt Ltd', 'SME BU', 'Arathi'),
  ('SLN Coffee Private Limited', 'India MM BU', 'Pavan'),
  ('Superior Drinks Private Limited', 'India MM BU', 'Prithee'),
  ('Tata Consumer Products Limited', 'India Ent BU', 'Pavan'),
  ('C.P.Milk & Food Products Private Limited', 'India MM BU', 'Salbi'),
  ('Gatbro International Ltd', 'India MM BU', 'Pavan'),
  ('Dhathri Ayurveda Private Limited', 'SME BU', 'Arathi'),
  ('Timex Group India Limited', 'India Ent BU', 'Juliya'),
  ('Jyothy Labs Limited (ISD)', 'India Ent BU', 'Prithee'),
  ('Coca-Cola India Private Limited', 'India MM BU', 'Prithee'),
  ('Manjilas Food Tech Pvt Ltd', 'India MM BU', 'Pavan'),
  ('V K Belting Pvt Ltd', 'India MM BU', 'Salbi'),
  ('Ava Naturals Private Limited', 'India MM BU', 'Juliya'),
  ('DD Shah Food Labs LLP', 'SME BU', 'Arathi'),
  ('TOLINS TYRES LIMITED', 'SME BU', 'Arathi'),
  ('Puranchand Jain & Sons Private Limited', 'SME BU', 'Arathi'),
  ('New Vinco Corporation', 'SME BU', 'Arathi'),
  ('Lipleader Entercrop Private Limited', 'SME BU', 'Arathi'),
  ('Qunova Technologies Private Limited', 'SME BU', 'Arathi'),
  ('PT. Jiva Agriculture Indonesia', 'India MM BU', 'Pavan'),
  ('Globalbees Brands Private Limited', 'SME BU', 'Arathi'),
  ('Sunraja Oil Industries Private Limited', 'India MM BU', 'Pavan'),
  ('Pankaja Kasthuri Herbals India Private Limited', 'India MM BU', 'Juliya'),
  ('Amrutanjan Health Care Limited', 'India MM BU', 'Juliya'),
  ('Mapro Foods Private Limited', 'SME BU', 'Arathi'),
  ('Hygard Household Product Private Limited', 'SME BU', 'Arathi'),
  ('Silvassa Bottling Co', 'SME BU', 'Arathi'),
  ('Janani Family Care Private Limited', 'India MM BU', 'Salbi'),
  ('Gowdurbar Natural Products Private Limited', 'SME BU', 'Arathi'),
  ('Chip-Valley Foods Private Limited', 'SME BU', 'Arathi'),
  ('Mascot International Private Limited', 'SME BU', 'Arathi'),
  ('Gajraj Agrotech Private Limited', 'SME BU', 'Arathi'),
  ('Halonix Technologies Private Limited', 'India MM BU', 'Salbi'),
  ('Milk Mantra Dairy Private Limited', 'SME BU', 'Arathi'),
  ('Vikram Tea Processor Private Limited', 'India MM BU', 'Prithee'),
  ('Bauli India Bakes & Sweets Private Limited', 'India MM BU', 'Prithee'),
  ('Santhoshimathaa Edible Oils Refinery Private Limited', 'SME BU', 'Arathi'),
  ('Naturell India Private Limited', 'India MM BU', 'Prithee'),
  ('Annapurna Food And Beverages', 'India MM BU', 'Juliya'),
  ('Miror Therapeutics Private Limited', 'SME BU', 'Arathi'),
  ('Grand Oak Limited', 'MEA BU', 'Pavan'),
  ('Philips India Limited', 'India Ent BU', 'Salbi'),
  ('Philips India Limited (PH)', 'India Ent BU', 'Salbi'),
  ('United Distributors Incorporation', 'SME BU', 'Arathi'),
  ('AV Organics Private Limited', 'SME BU', 'Arathi'),
  ('Nureca Limited', 'SME BU', 'Arathi'),
  ('Protronics Distributors LLP', 'SME BU', 'Arathi'),
  ('Tube Investments of India Limited', 'India MM BU', 'Juliya'),
  ('Tramontina India Private Limited', 'SME BU', 'Arathi'),
  ('Sona Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Duval Enterprises Private Limited', 'SME BU', 'Arathi'),
  ('Binito Foods Private Limited', 'SME BU', 'Arathi'),
  ('Dolphin Foods India Limited', 'SME BU', 'Arathi'),
  ('Lohiya Edible Oils Private Limited', 'SME BU', 'Arathi'),
  ('G M Tea Packers Private Limited', 'SME BU', 'Arathi'),
  ('Morton Foods Limited', 'SME BU', 'Arathi'),
  ('Body Cupid Private Limited', 'India MM BU', 'Juliya'),
  ('Sirmaur Soaps And Allied Products Private Limited', 'SME BU', 'Arathi'),
  ('Tata Motors Limited', 'India Ent BU', 'Prithee'),
  ('Tata Motors Limited (Old)', 'India Ent BU', 'Prithee'),
  ('Tiger Food Ingredients Private Limited', 'SME BU', 'Arathi'),
  ('Creamline Dairy Products Limited', 'KAM BU', 'Pavan'),
  ('Premier Tissues India Limited', 'India MM BU', 'Pavan'),
  ('Lazer India Private Limited', 'SME BU', 'Arathi'),
  ('Sankethi Nutriments Private Limited', 'SME BU', 'Arathi'),
  ('Zea Maize Private Limited (4700bc)', 'SME BU', 'Arathi'),
  ('Cultgear Private Limited', 'India MM BU', 'Juliya'),
  ('Bergner Impex (India) Private Limited', 'SME BU', 'Arathi'),
  ('Super Bond Adhesives Pvt Ltd', 'SME BU', 'Arathi'),
  ('KM Oil Industries', 'SME BU', 'Arathi'),
  ('Nivea India Private Limited', 'India MM BU', 'Prithee'),
  ('Ramani Icecream Company Limited', 'India MM BU', 'Prithee'),
  ('Mahindra Summit Agriscience Limited', 'India Ent BU', 'Prithee'),
  ('B.N. Agritech Limited', 'SME BU', 'Arathi'),
  ('Mankind Consumer Products Private Limited', 'India Ent BU', 'Salbi'),
  ('Ambitech Healthcare Private Limited', 'SME BU', 'Arathi'),
  ('Ample Foods Private Limited', 'SME BU', 'Arathi'),
  ('Duraent Lifesciences LLP', 'SME BU', 'Arathi'),
  ('Natch Products And Services Private Limited', 'SME BU', 'Arathi'),
  ('Twenty Twenty Food Products', 'SME BU', 'Arathi'),
  ('Safari Industries India Limited', 'India MM BU', 'Prithee'),
  ('Familycare Consumer Private Limited', 'India MM BU', 'Juliya'),
  ('Budge Budge Refineries Limited', 'SME BU', 'Arathi'),
  ('Bankai Agrifood Private Limited', 'India MM BU', 'Prithee'),
  ('Anna B Creations Private Limited', 'ERTM', 'Arathi'),
  ('Spark International (RS Square)', 'SME BU', 'Arathi'),
  ('Kamal Healthcare Products Private Limited', 'SME BU', 'Arathi'),
  ('Mysoredeep Perfumery House', 'India MM BU', 'Prithee'),
  ('Mjengo Limited', 'MEA BU', 'Pavan'),
  ('Vasant Masala Private Limited', 'SME BU', 'Arathi'),
  ('Ess Kay Beauty Resources Private Limited', 'SME BU', 'Arathi'),
  ('Walko QSR Company Private Limited', 'India MM BU', 'Juliya'),
  ('Mondelez India Foods Private Limited', 'SME BU', 'Arathi'),
  ('Ygiis Foods And Beverages Private Limited', 'SME BU', 'Arathi'),
  ('GANESH FOOD PRODUCTS PRIVATE LIMITED', 'SME BU', 'Arathi'),
  ('Udaipur Beverages Limited', 'India MM BU', 'Prithee'),
  ('Louis Dreyfus Company India Private Limited', 'India Ent BU', 'Juliya'),
  ('JK Files & Engineering Limited', 'India Ent BU', 'Prithee'),
  ('Archian Foods Private Limited', 'India MM BU', 'Juliya'),
  ('Kings Foodtech Private Limited', 'SME BU', 'Arathi'),
  ('Kesseboehmer Furniture Fittings India Private Limited', 'SME BU', 'Arathi'),
  ('Plaza Wires Limited', 'SME BU', 'Arathi'),
  ('K Pra Foods Private Limited', 'SME BU', 'Arathi'),
  ('Balajee NP Pvt Ltd', 'SME BU', 'Arathi'),
  ('Welable Pharma', 'SME BU', 'Arathi'),
  ('VTC Tradewings Private Limited', 'SME BU', 'Arathi'),
  ('Shri Sai Samarth Agencies', 'SME BU', 'Arathi'),
  ('KLF Nirmal Industries Private Limited', 'SME BU', 'Arathi'),
  ('Aryanveda Cosmeceuticals', 'SME BU', 'Arathi'),
  ('Beacon Power Systems', 'SME BU', 'Arathi'),
  ('Premium Soap And Detergent Industry LLP', 'SME BU', 'Arathi'),
  ('Terrestrial Foods Limited', 'India MM BU', 'Salbi'),
  ('Aaditya Food Products (Ramani)', 'India MM BU', 'Prithee'),
  ('Mimansa Industries Private Limited', 'SME BU', 'Arathi'),
  ('Bhaskar Venkatesh Products Private Limited', 'SME BU', 'Arathi'),
  ('Jai Beverages Private Limited', 'India MM BU', 'Juliya'),
  ('Chandra Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Sri Sadananda Foods Private Limited', 'SME BU', 'Arathi'),
  ('Infinity Global Industries Private Limited', 'SME BU', 'Arathi'),
  ('Shri Raja Industries (Prema Mathivanan)', 'SME BU', 'Arathi'),
  ('Naga Limited', 'India MM BU', 'Pavan'),
  ('Me n Moms Private Limited', 'India MM BU', 'Prithee'),
  ('R For Rabbit Baby Products Private Limited', 'SME BU', 'Arathi'),
  ('Fena Private Limited', 'India MM BU', 'Salbi'),
  ('Hamilton Housewares Private Limited', 'India MM BU', 'Juliya'),
  ('Varasidhi Enterprises', 'SME BU', 'Arathi'),
  ('Selzer Innovex Private Limited', 'India MM BU', 'Juliya'),
  ('Redcliffe Hygiene Private Limited (Peesafe)', 'SME BU', 'Arathi'),
  ('Emami Agrotech Limited', 'India Ent BU', 'Juliya'),
  ('East West Seed (Hai Mui Ten Do) Co. Ltd', 'SEA BU', 'Juliya'),
  ('Godrej Consumer Products Ltd - Nepal', 'KAM BU', 'Salbi'),
  ('Brajeshwori Industries Pvt. Ltd.', 'India MM BU', 'Salbi'),
  ('Food Service (India) Private Limited', 'SME BU', 'Arathi'),
  ('Begwani Group', 'SME BU', 'Arathi'),
  ('Bentec India Limited', 'SME BU', 'Arathi'),
  ('Geksons Nutrition LLP', 'SME BU', 'Arathi'),
  ('Saintevia Foods Private Limited', 'SME BU', 'Arathi'),
  ('TUV SUD South Asia Private Limited', 'SME BU', 'Arathi'),
  ('Babylove Sanitary Products and Packaging Limited', 'MEA BU', 'Juliya'),
  ('Narang Access Private Limited', 'SME BU', 'Arathi'),
  ('Pavizham Oil And Foods', 'SME BU', 'Arathi'),
  ('CHI Pharmaceuticals Limited - (TGI Group)', 'MEA BU', 'Pavan'),
  ('Good Roots Kitchenware Private Limited', 'SME BU', 'Arathi'),
  ('The Capital Maharaja Organisation Limited', 'India Ent BU', 'Pavan'),
  ('Nysa Consumer Products Private Limited', 'SME BU', 'Arathi'),
  ('Hyuga Health & Wellness Private Limited', 'ERTM', 'Arathi'),
  ('SSG Pharma Private Limited', 'SME BU', 'Arathi'),
  ('Unifuds India Private Limited', 'SME BU', 'Arathi'),
  ('Inframandi Technologies Private Limited', 'SME BU', 'Arathi'),
  ('Samyog Health Foods Private Limited', 'SME BU', 'Arathi'),
  ('Narmada Drinks Private Limited', 'India MM BU', 'Prithee'),
  ('Glenmark Pharmaceuticals Limited', 'India MM BU', 'Prithee'),
  ('GRM Foodkraft Private Limited', 'SME BU', 'Arathi'),
  ('BPL Medical Technologies Private Limited', 'SME BU', 'Arathi'),
  ('Reckitt Benckiser (India) Private Limited', 'MEA BU', 'Salbi'),
  ('Prayagh Nutri Products Private Limited', 'India MM BU', 'Pavan'),
  ('360 Degree Supply Chain Management Private Limited', 'SME BU', 'Arathi'),
  ('Luxottica India Eyewear Private Limited', 'India Ent BU', 'Juliya'),
  ('Swastik Mirch Store', 'SME BU', 'Arathi'),
  ('Adjavis Venture Limited', 'SME BU', 'Arathi'),
  ('Bausch & Lomb India Private Limited', 'India Ent BU', 'Salbi'),
  ('Said Salim Bakhresa & Co. Ltd', 'MEA BU', 'Salbi'),
  ('Sanghvi Foods Private Limited', 'SME BU', 'Arathi'),
  ('Kerala Ayurveda Limited', 'SME BU', 'Arathi'),
  ('Frigorifico Allana Private Limited', 'India MM BU', 'Prithee'),
  ('Navabharat Limited', 'SME BU', 'Arathi'),
  ('Ultima Search', 'SME BU', 'Arathi'),
  ('Ithiki Technologies Private Limited', 'SME BU', 'Arathi'),
  ('Mars International India Private Limited', 'India Ent BU', 'Salbi'),
  ('Laljee Godhoo & Co', 'SME BU', 'Arathi'),
  ('Pro Body Balance Private Limited (Pittie Group)', 'India MM BU', 'Juliya'),
  ('GG Organics Care Private Limited', 'SME BU', 'Arathi'),
  ('Pagariya Food Products Private Limited', 'SME BU', 'Arathi'),
  ('Kanan Devan Hills Plantations Company Private Limited', 'India MM BU', 'Juliya'),
  ('Dhariwal Food', 'SME BU', 'Arathi'),
  ('Merino Industries Limited', 'India Ent BU', 'Salbi'),
  ('Pan Parag India Limited', 'India MM BU', 'Salbi'),
  ('Bluetail GTM India Private Limited', 'SME BU', 'Arathi'),
  ('Stanvac Prime Private Limited', 'SME BU', 'Arathi'),
  ('Fitshit Health Solutions Private Limited', 'SME BU', 'Arathi'),
  ('Diet Fibre 365 Food Products Private Limited', 'SME BU', 'Arathi'),
  ('Core De Industries (Rishi Sanjay Korde)', 'SME BU', 'Arathi'),
  ('M. B. Beverages (India) Limited', 'SME BU', 'Arathi'),
  ('Graviss Foods Private Limited', 'India MM BU', 'Prithee'),
  ('Dev Milk Foods Private Limited', 'SME BU', 'Arathi'),
  ('Puraforma Foods Private Limited', 'ERTM', 'Arathi'),
  ('Langar Bidi Company Poona', 'SME BU', 'Arathi'),
  ('Mahashakti Soap & Chemical Ind. Pvt. Ltd.', 'SME BU', 'Arathi'),
  ('Sunbeam Merchantile Ventures P Ltd', 'SME BU', 'Arathi'),
  ('Hyderabad Food Products Private Limited', 'SME BU', 'Arathi'),
  ('AB Industries', 'SME BU', 'Arathi'),
  ('Ghodawat Consumer Limited', 'SME BU', 'Arathi'),
  ('Joyo Plastics', 'SME BU', 'Arathi'),
  ('Quadrant Consumer Products LLP', 'SME BU', 'Arathi'),
  ('Trusha Tea Marketing Private Limited', 'SME BU', 'Arathi'),
  ('MilkLane Dairy Services Private Limited', 'SME BU', 'Arathi'),
  ('Shri Balaji Incense Industries', 'SME BU', 'Arathi'),
  ('Sri Aishwarya Food Industries Private Limited', 'SME BU', 'Arathi'),
  ('Nirmal Polyplast Private Limited', 'SME BU', 'Arathi'),
  ('Foods And Inns Limited', 'India MM BU', 'Prithee'),
  ('Arora Foods India', 'SME BU', 'Arathi'),
  ('DRB Foods Private Limited', 'SME BU', 'Arathi'),
  ('Bengaluru Co-Operative Milk Union Limited', 'SME BU', 'Arathi'),
  ('Midas Hygiene Industries Private Limited', 'India MM BU', 'Prithee'),
  ('Srivari Spices And Foods Limited', 'SME BU', 'Arathi'),
  ('VB Brothers Pvt Ltd', 'India MM BU', 'Arathi'),
  ('Kotak Hygienic Products LLP', 'SME BU', 'Arathi'),
  ('VST Industries Limited', 'India Ent BU', 'Pavan'),
  ('United Breweries Limited', 'India Ent BU', 'Pavan'),
  ('Anmol Industries Limited', 'India MM BU', 'Salbi'),
  ('Orient Electric Limited', 'India Ent BU', 'Salbi'),
  ('Idam Natural Wellness Private Limited', 'India MM BU', 'Salbi'),
  ('PT Godrej Consumer Products Indonesia', 'SEA BU', 'Pavan'),
  ('Indo Nissin Foods Private Limited', 'India Ent BU', 'Pavan'),
  ('Coca-Cola Beverages Vietnam Limited', 'SEA BU', 'Pavan'),
  ('Imagine Marketing Limited', 'India MM BU', 'Salbi'),
  ('A O Smith India Water Products Private Limited', 'India MM BU', 'Pavan'),
  ('Sapat Global Health Private Limited', 'SME BU', 'Arathi'),
  ('Delicia Foods (Monginis Foods)', 'SME BU', 'Arathi'),
  ('Swadeshi Food & Bevarages (Mohammed Athaulla Bantwal)', 'SME BU', 'Arathi'),
  ('Octagon Foods Private Limited', 'SME BU', 'Arathi'),
  ('Colgate Palmolive India Ltd', 'India Ent BU', 'Salbi'),
  ('Bazana Foods Private Limited', 'SME BU', 'Arathi'),
  ('100Percent Nourishment Private Limited', 'SME BU', 'Arathi'),
  ('Parmanand & Sons Food Products Private Limited', 'SME BU', 'Arathi'),
  ('Dhamija Grinders Private Limited', 'SME BU', 'Arathi'),
  ('Pro Nature Organic Foods Private Limited', 'SME BU', 'Arathi'),
  ('Ana Oils and Fats India Private Limited', 'SME BU', 'Arathi'),
  ('Parisons Foods Private Limited', 'SME BU', 'Arathi'),
  ('Devata Associates', 'SME BU', 'Arathi'),
  ('Jeevitha Enterprises', 'SME BU', 'Arathi'),
  ('Rahul Group', 'India MM BU', 'Salbi'),
  ('Vanita Foods Private Limited', 'SME BU', 'Arathi'),
  ('Figo India Private Limited', 'SME BU', 'Arathi'),
  ('Gadre Marine Export Private Limited', 'SME BU', 'Arathi'),
  ('Balaji Electronics (Durai Raj Srinivasalu Naidu)', 'SME BU', 'Arathi'),
  ('Upper Crust Cuisines And Events Private Limited', 'SME BU', 'Arathi'),
  ('JIS Farms Private Limited', 'SME BU', 'Arathi'),
  ('Plaza Wires Private Limited', 'SME BU', 'Arathi'),
  ('Ashoka Foam Multi Plast Limited', 'SME BU', 'Arathi'),
  ('Aditi Toys Private Limited', 'SME BU', 'Arathi'),
  ('Pristine Ingredients Private Limited', 'SME BU', 'Arathi'),
  ('United Enterprises', 'SME BU', 'Arathi'),
  ('Maharaj Soaps Industry Private Limited', 'SME BU', 'Arathi'),
  ('Anegudde Upadhyaya Industries', 'SME BU', 'Arathi'),
  ('Saksham Impex Private Limited', 'SME BU', 'Arathi'),
  ('Green Valley Food Processors Private Limited', 'SME BU', 'Arathi'),
  ('Sundrop Brands Limited', 'India Ent BU', 'Juliya'),
  ('Popular Marketing Company', 'SME BU', 'Arathi'),
  ('Vijay Solvex Limited', 'SME BU', 'Arathi'),
  ('SWG Industries Limited', 'SME BU', 'Arathi'),
  ('Ishwar Raj Beverages Private Limited', 'SME BU', 'Arathi'),
  ('PT YOU Indonesia', 'SEA BU', 'Pavan'),
  ('Hindusthan Speciality Chemicals Limited', 'SME BU', 'Arathi'),
  ('Effeza Science Private Limited', 'SME BU', 'Arathi'),
  ('Pravek Kalp Private Limited', 'India MM BU', 'Salbi'),
  ('Nambisans Dairy Private Limited', 'SME BU', 'Arathi'),
  ('Vivala Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Health Care Medicines (Surinder Pal)', 'SME BU', 'Arathi'),
  ('Tasty Bite Eatables Limited', 'SME BU', 'Arathi'),
  ('Risshta Foods Private Limited', 'SME BU', 'Arathi'),
  ('SHS Global', 'SME BU', 'Arathi'),
  ('Om Sree Marketing Solutions Private Limited', 'SME BU', 'Arathi'),
  ('Asmita Super Markets Private Limited', 'SME BU', 'Arathi'),
  ('Rama Pashu Aahar Pvt Ltd', 'SME BU', 'Arathi'),
  ('SatisComm (India) Private Limited', 'SME BU', 'Arathi'),
  ('United Brothers Company (U.B Co.)', 'SME BU', 'Arathi'),
  ('Abdos Consumer Care Limited', 'SME BU', 'Arathi'),
  ('R L Corp India (Pawan Kumar Choudhary)', 'India MM BU', 'Juliya'),
  ('Y P Spices Private Limited', 'SME BU', 'Arathi'),
  ('Simran Nutrifoods Private Limited', 'SME BU', 'Arathi'),
  ('Sri Sai Beverages (Hemavathi Suresh)', 'SME BU', 'Arathi'),
  ('Chromachemie Laboratory Private Limited', 'SME BU', 'Arathi'),
  ('Daddy Dairy India Private Limited', 'SME BU', 'Arathi'),
  ('Methods Automotive Private Limited', 'SME BU', 'Arathi'),
  ('West-In Avo Private Limited', 'SME BU', 'Arathi'),
  ('Nutriglow GBL Lifesciences Pvt. Ltd.', 'SME BU', 'Arathi'),
  ('Mother Sparsh Baby Care Private Limited', 'SME BU', 'Arathi'),
  ('S L K Food Processing', 'SME BU', 'Arathi'),
  ('Sree Vyshnavi Ellvin Industries Private Limited', 'SME BU', 'Arathi'),
  ('Dugar Consumer Products Private Limited', 'SME BU', 'Arathi'),
  ('OVO FARM PRIVATE LIMITED', 'SME BU', 'Arathi'),
  ('Sahyadri Bio Labs Private Limited', 'SME BU', 'Arathi'),
  ('Pringle Homeware Private Limited', 'SME BU', 'Arathi'),
  ('Grand Foods India', 'SME BU', 'Arathi'),
  ('Dileo Care India Private Limited', 'SME BU', 'Arathi'),
  ('Sri Sanjai Food Industries', 'SME BU', 'Arathi'),
  ('Crop Growth (India) Pvt Ltd', 'SME BU', 'Arathi'),
  ('Asha Bakers & Confectioners (Jyoti Prakash Chhabria)', 'SME BU', 'Arathi'),
  ('Sweet Karam Coffee India Private Limited', 'SME BU', 'Arathi'),
  ('India Sweet Co P Ltd', 'SME BU', 'Arathi'),
  ('Hasiru Foods Private Limited', 'SME BU', 'Arathi'),
  ('Shri Balaji Overseas', 'SME BU', 'Arathi'),
  ('Trucare Hygiene (India) Private Limited', 'SME BU', 'Arathi'),
  ('Keeline Appliances Private Limited', 'SME BU', 'Arathi'),
  ('Vinayak Electrical Industries (Jayeshkumar Hasmukhlal Katariya)', 'SME BU', 'Arathi'),
  ('Aruna Industries', 'SME BU', 'Arathi'),
  ('Maxvita Foods India Private Limited', 'SME BU', 'Arathi'),
  ('Mahalaxmi Sales & Marketing', 'SME BU', 'Arathi'),
  ('Bansal Extraction And Exports Private Limited', 'SME BU', 'Arathi'),
  ('UD Food Products Private Limited', 'SME BU', 'Arathi'),
  ('S P POLYMERS', 'SME BU', 'Arathi'),
  ('Agrileaf Exports Private Limited', 'SME BU', 'Arathi'),
  ('Naturise Consumer Products Private Limited', 'SME BU', 'Arathi'),
  ('The Waxpol Industries Limited', 'SME BU', 'Arathi'),
  ('Anmol Minerals Pvt Ltd', 'SME BU', 'Arathi'),
  ('Bimala Spices Food Industries Private Limited', 'SME BU', 'Arathi'),
  ('Puramate India Private Limited', 'SME BU', 'Arathi'),
  ('ACE Beveragez Private Limited', 'SME BU', 'Arathi'),
  ('Sahuwala Flour Mills', 'SME BU', 'Arathi'),
  ('Harmony Remedies India Private Limited', 'SME BU', 'Arathi'),
  ('Anmol Healthcare Private Limited', 'SME BU', 'Arathi'),
  ('Aussee Oats India Private Limited', 'SME BU', 'Arathi'),
  ('A. N. R. LIGHTING PRIVATE LIMITED', 'SME BU', 'Arathi'),
  ('Shree Kailash Grain Mills Private limited', 'SME BU', 'Arathi'),
  ('Oxley Limited', 'SME BU', 'Arathi'),
  ('Marvelle Health Care Private Limited', 'SME BU', 'Arathi'),
  ('Padmini Impex Pvt Ltd', 'SME BU', 'Arathi'),
  ('Moonfreeze Foods Private Limited', 'SME BU', 'Arathi'),
  ('D C Johar And Sons Private Limited', 'SME BU', 'Arathi'),
  ('Xanadu Fine Foodstuff LLP', 'SME BU', 'Arathi'),
  ('Premier Alcobev Private Limited', 'SME BU', 'Arathi'),
  ('Habitbev Private Limited', 'SME BU', 'Arathi'),
  ('Spectra & Star Convergence Limited', 'SME BU', 'Arathi'),
  ('Asianlak Health Foods Ltd', 'SME BU', 'Arathi'),
  ('Kumar Beverages Industries', 'SME BU', 'Arathi'),
  ('Nav Shikha Polypack Industries Private Limited', 'SME BU', 'Arathi'),
  ('JP Distilleries Private Limited', 'SME BU', 'Arathi'),
  ('Signet Enterprises', 'SME BU', 'Arathi'),
  ('Grainotch Industries Limited', 'SME BU', 'Arathi'),
  ('Agrow Distributors', 'SME BU', 'Arathi'),
  ('NIF Private Limited', 'India MM BU', 'Salbi'),
  ('Dharampal Satyapal Limited', 'India MM BU', 'Salbi'),
  ('Kairos Super Foods Private Limited', 'SME BU', 'Arathi'),
  ('Atul Limited', 'SME BU', 'Arathi'),
  ('Sundarbans Food Products (I) Pvt Ltd', 'India MM BU', 'Juliya'),
  ('Dhiraj Agro Private Limited', 'SME BU', 'Arathi'),
  ('Greendot Health Foods Private Limited', 'India MM BU', 'Juliya'),
  ('Dugar Food & Beverage Private Limited', 'SME BU', 'Arathi'),
  ('Cultsport Private Limited', 'India MM BU', 'Juliya'),
  ('Shantinath Detergents Pvt Ltd', 'India MM BU', 'Salbi'),
  ('Dharampal Satyapal Foods Limited', 'India MM BU', 'Salbi'),
  ('Ayoka Global Private Limited', 'SME BU', 'Arathi'),
  ('Allana Consumer Products (Tiffany)', 'India MM BU', 'Prithee'),
  ('KL Beverages (Udayak Agro)', 'SME BU', 'Arathi'),
  ('Harvestland Beverages Private Limited', 'India MM BU', 'Juliya'),
  ('Monica Products', 'SME BU', 'Arathi'),
  ('FNI Spices Private Limited', 'SME BU', 'Arathi'),
  ('Protech Appliances Private Limited', 'SME BU', 'Arathi'),
  ('Ocean Drinks Private Limited', 'SME BU', 'Arathi'),
  ('Satez Agro Products Private Limited', 'India MM BU', 'Juliya'),
  ('Shubhkart India Private Limited (Pro Body)', 'India MM BU', 'Juliya'),
  ('Dharampal Premchand Ltd', 'India MM BU', 'Salbi'),
  ('Maharani Dall Mill Contractors Sri Maharani Dall Producers', 'SME BU', 'Arathi'),
  ('Leayan Global Private Limited', 'India MM BU', 'Salbi'),
  ('Kanin Industries Private Limited', 'SME BU', 'Arathi'),
  ('Gandhi Spices Private Limited', 'SME BU', 'Arathi'),
  ('Swaad Foods', 'SME BU', 'Arathi'),
  ('TVM EDIBLE OIL REFINERIES PRIVATE LIMITED', 'SME BU', 'Arathi'),
  ('Asianlak Health Foods Ltd (Unit-II)', 'SME BU', 'Arathi'),
  ('British American Shared Services (GSD) Limited', 'BAT BU', 'Pavan'),
  ('Dairy Gold Limited (Trade Kings Group)', 'MEA BU', 'Pavan'),
  ('Excel Energy Project Management Services', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (ARSUS Global)', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (BML)', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (IDL)', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (Redbull)', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited - NigerBev Ltd', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited GBP (STL)', 'MEA BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (India)', 'KAM BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (India) GBP', 'KAM BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (Malaysia)', 'KAM BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (Vietnam)', 'KAM BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (Vietnam) GBP', 'KAM BU', 'Pavan'),
  ('Stoneslane Portal L.L.C', 'MEA BU', 'Pavan'),
  ('Swiss Bake Limited  (Trade Kings Group)', 'MEA BU', 'Pavan'),
  ('Trade Kings Zimbabwe Pvt.Ltd.', 'MEA BU', 'Pavan'),
  ('Yoyo Foods Limited (Trade Kings Group)', 'MEA BU', 'Pavan'),
  ('Sintex-BAPL Limited', 'India Ent BU', 'Salbi'),
  ('Yaashkrishni Food Science Limited', 'India MM BU', 'Arathi'),
  ('Brinton Pharmaceuticals Limited', 'SME BU', 'Arathi'),
  ('Emme Exporters (Mohamed Asharaf Abdul Rahiman Mulamparambil)', 'SME BU', 'Arathi'),
  ('Coca-Cola Pinya Beverages Myanmar Ltd', 'SEA BU', 'Prithee'),
  ('Gulkis Comércio E Indústria LDA', 'SME BU', 'Arathi'),
  ('Shivani Detergents Private Limited', 'India MM BU', 'Prithee'),
  ('Godrej And Boyce Manufacturing Co Ltd', 'KAM BU', 'Prithee'),
  ('TGI Distri Limited', 'MEA BU', 'Pavan'),
  ('Godrej Tyson Foods Limited (New)', 'India Ent BU', 'Pavan'),
  ('HR Food Processing Private Limited (Osam Dairy)', 'India MM BU', 'Salbi'),
  ('Teamlease Services Limited (Old)', 'India Ent BU', 'Pavan'),
  ('EPICU Beverages Private Limited (New)', 'SME BU', 'Arathi'),
  ('Shree Ganesh Bakery Nandani Private Limited (Chakote Group)', 'India MM BU', 'Prithee'),
  ('Philips India Limited (Respironics)', 'India Ent BU', 'Salbi'),
  ('Mondelez India Foods Private Limited (ONDC)', 'ERTM', 'Arathi'),
  ('Archian Foods Private Limited (Lahori Zeera)', 'India MM BU', 'Juliya'),
  ('Redcliffe Hygiene Private Limited (Peesafe) (Old)', 'SME BU', 'Arathi'),
  ('Nysa Consumer Products Private Limited (Srigdhaa)', 'SME BU', 'Arathi'),
  ('SSG Pharma Private Limited (Satmola)', 'SME BU', 'Arathi'),
  ('Imagine Marketing Limited (New)', 'India MM BU', 'Salbi'),
  ('NIF Private Limited (Namaste India)', 'India MM BU', 'Salbi'),
  ('Shantinath Detergents Pvt Ltd (Safechem)', 'India MM BU', 'Salbi'),
  ('Kanin Industries Private Limited (Kangaro)', 'SME BU', 'Arathi'),
  ('J G Hosiery Private Limited', 'India MM BU', 'Nicky'),
  ('Godrej Consumer Products Ltd - Africa', 'KAM BU', 'Pavan'),
  ('Syska Led Lights Private Limited', 'SME BU', 'Arathi'),
  ('Lifespice India Private Limited', 'SME BU', 'Arathi'),
  ('CG Foods Nepal Limited', 'India Ent BU', 'Salbi'),
  ('Vibhava Marketing Corporation Private Limited', 'India MM BU', 'Juliya'),
  ('Merhaki Foods And Nutrition Private Limited', 'SME BU', 'Arathi'),
  ('Shell International Petroleum Company Limited', 'KAM BU', 'Pavan'),
  ('Allana Consumer Products Limited', 'India MM BU', 'Prithee'),
  ('Tube Investments of India Limited - TIDC', 'India MM BU', 'Juliya'),
  ('Terrestrial Foods Limited (JK Foods)', 'India MM BU', 'Salbi'),
  ('CHI Pharmaceuticals Limited', 'MEA BU', 'Pavan'),
  ('Tube Investments of India Limited - Main', 'India MM BU', 'Juliya'),
  ('Maharani Dall Mill Contractors Sri Maharani Dall Producers (Tenali Double Horse)', 'SME BU', 'Arathi'),
  ('Dhanalakshmi Srinivasan Sugars Private Limited (VV Sugar)', 'SME BU', 'Arathi'),
  ('Candex Solution India Private Limited', 'India Ent BU', 'Salbi'),
  ('Avanti Pet Care Private Limited', 'SME BU', 'Arathi'),
  ('Lagom Labs Private Limited', 'SME BU', 'Arathi'),
  ('Globalstyle Technologies Private Limited', 'SME BU', 'Arathi'),
  ('Mankind Petcare Private Limited', 'India Ent BU', 'Salbi'),
  ('Mankind Pharma Limited', 'India Ent BU', 'Salbi'),
  ('Greendot Health Foods Private Limited(Cornitos)', 'India MM BU', 'Juliya'),
  ('Okaya Power Private Limited', 'India Ent BU', 'Salbi'),
  ('Dhampur Bio Organics Limited', 'SME BU', 'Arathi'),
  ('GRB Dairy Foods Private Limited (Main)', 'India MM BU', 'Juliya'),
  ('Mzuri Sweets Limited', 'MEA BU', 'Prithee'),
  ('Ramdev Food Products Private Limited (New)', 'India MM BU', 'Prithee'),
  ('Dharampal Satyapal Foods Limited (New)', 'India MM BU', 'Salbi'),
  ('Kim-Fay East Africa Limited', 'SME BU', 'Arathi'),
  ('Sriveda Sattva Private Limited (Sri Sri Ayurveda Trust)', 'SME BU', 'Arathi'),
  ('Prayagh Consumer Care Private Limited(PCCPL)', 'India MM BU', 'Pavan'),
  ('Stellaris Specialities India Limited', 'SME BU', 'Arathi'),
  ('Sales Walk & Co', 'India MM BU', 'Juliya'),
  ('Guardian Healthcare Services Private Limited (GNC)', 'SME BU', 'Arathi'),
  ('Indepesca Overseas Private Limited', 'SME BU', 'Arathi'),
  ('Excite Panacea Limited - NigerBev Ltd  (Old)', 'MEA BU', 'Pavan'),
  ('PBI India Private Limited', 'SME BU', 'Arathi'),
  ('Shri Sai Samarth Agencies (Nectar)', 'SME BU', 'Arathi'),
  ('United Associates', 'SME BU', 'Arathi'),
  ('M K Exim India Limited (Lewanna)', 'SME BU', 'Arathi'),
  ('Tuareg Marketing Private Limited (INALSA)', 'SME BU', 'Arathi'),
  ('Ravi Foods Private Limited (old)', 'India MM BU', 'Pavan'),
  ('Playpipers Industries LLP', 'SME BU', 'Arathi'),
  ('Nutriglow GBL Lifesciences Pvt. Ltd. (Old)', 'SME BU', 'Arathi'),
  ('Merino Industries Limited (Old)', 'India Ent BU', 'Salbi'),
  ('Granmav Enterprises (Trofi)', 'SME BU', 'Arathi'),
  ('Tube Investments of India Limited - TI Macho', 'India MM BU', 'Juliya'),
  ('Bright Lifecare Private Limited (Healthkart)', 'India MM BU', 'Salbi'),
  ('Refreshment Product Service India Private Limited', 'India Ent BU', 'Pavan'),
  ('H D Wire Private Limited', 'SME BU', 'Arathi'),
  ('ABT Industries Limited', 'India MM BU', 'Pavan'),
  ('Godrej Foods Limited', 'India Ent BU', 'Pavan'),
  ('Crystal Cook N Serve Products Private Limited', 'SME BU', 'Arathi'),
  ('Pramukh Industries', 'SME BU', 'Arathi'),
  ('Popular Traders', 'SME BU', 'Arathi'),
  ('Kilban Foods (India) Pvt Ltd', 'SME BU', 'Arathi'),
  ('Gujarat Foodtech LLP', 'SME BU', 'Arathi'),
  ('Rossari Biotech Limited', 'India MM BU', 'Prithee'),
  ('Adora Products Limited', 'MEA BU', 'Pavan'),
  ('ABT Industries Limited (Dairy Division)', 'India MM BU', 'Pavan'),
  ('TPF Bharat Private Limited', 'SME BU', 'Arathi'),
  ('Haltsons Corporation', 'SME BU', 'Arathi'),
  ('PT Dewa Tunggal Abadi', 'SEA BU', 'Arathi'),
  ('Al Saiee General Trading LLC- SP', 'MEA BU', 'Pavan'),
  ('ANR Designer Tiles Limited', 'SME BU', 'Arathi'),
  ('Bioweal Products Private Limited', 'SME BU', 'Arathi'),
  ('Sanwariya Foods and Snacks Pvt. Ltd.', 'India MM BU', 'Salbi'),
  ('Edible Products India Limited', 'SME BU', 'Arathi'),
  ('TI Medical Private Limited (New)', 'India MM BU', 'Salbi'),
  ('Anand Sweets And Savouries LLP', 'SME BU', 'Arathi'),
  ('CG Cement Industries Palpa Pvt Ltd.', 'India Ent BU', 'Salbi'),
  ('Beiersdorf India Private Limited (Old)', 'India MM BU', 'Prithee'),
  ('Maggemane Foods LLP', 'SME BU', 'Arathi'),
  ('J S Foods', 'SME BU', 'Arathi'),
  ('Coca-Cola Refreshments Malaysia Sdn. Bhd', 'SEA BU', 'Pavan'),
  ('Micks Products LLP', 'SME BU', 'Arathi'),
  ('Carlsberg India Private Limited', 'India Ent BU', 'Salbi'),
  ('Ebco Private Limited', 'India Ent BU', 'Prithee'),
  ('Everest Stabilisers Private Limited', 'SME BU', 'Arathi'),
  ('Allied Natural Product', 'SME BU', 'Arathi'),
  ('Amalgamated Breweries Private Limited', 'SME BU', 'Arathi'),
  ('Amplifon (India) Private Limited', 'SME BU', 'Arathi'),
  ('Ananda Dairy Limited', 'India MM BU', 'Salbi'),
  ('JK Maini Precision Technology Limited', 'India Ent BU', 'Prithee'),
  ('Goa Medicos Private Limited', 'SME BU', 'Arathi'),
  ('Vini Cosmetics Private Limited', 'India Ent BU', 'Pavan'),
  ('Monica Products (Gloria Ice Cream)', 'SME BU', 'Arathi'),
  ('Foods And Inns Limited (New)', 'India MM BU', 'Prithee'),
  ('Econaturals', 'SME BU', 'Arathi'),
  ('Shalimar Incense Private Limited', 'India MM BU', 'Juliya'),
  ('SIDS Farm Private Limited', 'SME BU', 'Arathi'),
  ('Mahalaxmi Industries', 'SME BU', 'Arathi'),
  ('Vihana Health Care LLP', 'India MM BU', 'Salbi'),
  ('Godrej Pet Care Limited', 'India Ent BU', 'Pavan'),
  ('Alkai Power Solutions Limited', 'SME BU', 'Arathi'),
  ('VP Snacks Private Limited', 'SME BU', 'Arathi'),
  ('Sri Lakshmi Venkateshwara Enterprises', 'SME BU', 'Arathi'),
  ('Star Bottling & Cement Traders', 'SME BU', 'Arathi'),
  ('Mawana Foods Private Limited', 'SME BU', 'Arathi'),
  ('Orrego Natural', 'SME BU', 'Arathi'),
  ('Soyug Limited', 'SME BU', 'Arathi'),
  ('Zorabian Chicks Pvt.Ltd.', 'SME BU', 'Arathi'),
  ('GEF Foods India Private Limited', 'India MM BU', 'Pavan'),
  ('Indiraa Foods', 'SME BU', 'Arathi'),
  ('Mobisy Technologies UK Limited', 'Central', NULL),
  ('Chanakya Dairy Products Private Limited', 'SME BU', 'Arathi'),
  ('Nebico Limited', 'India MM BU', 'Arathi'),
  ('Zydus Wellness Products Limited', 'India MM BU', 'Prithee'),
  ('SNA Milk And Milk Products Limited', 'SME BU', 'Arathi'),
  ('Deccan Grainz Private Limited', 'SME BU', 'Arathi'),
  ('Hello Baby Private Limited', 'SME BU', 'Arathi'),
  ('Excite Panacea Limited GBP (STL)', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (BML)', 'MEA BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (India)', 'KAM BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (Vietnam)', 'KAM BU', 'Pavan'),
  ('Excite Panacea Limited - NigerBev Ltd', 'MEA BU', 'Pavan'),
  ('Excite Panacea Limited (Redbull)', 'MEA BU', 'Pavan'),
  ('Shell International Petroleum Company Limited (Malaysia)', 'KAM BU', 'Pavan'),
  ('British American Shared Services (GSD) Limited', 'BAT BU', 'Pavan'),
  ('Excite Panacea Limited (IDL)', 'MEA BU', 'Pavan'),
  ('Kiran Shoes Manufacturers (Goldstar)', 'SME BU', 'Arathi'),
  ('BIKANERVALA FOODS PRIVATE LIMITED', 'India MM BU', 'Juliya'),
  ('Jyoti India Kitchensink Private Limited', 'SME BU', 'Arathi'),
  ('Mavee Foods', 'SME BU', 'Arathi'),
  ('Tube Investments of India Limited -  TI Macho', 'India MM BU', 'Juliya'),
  ('Dharampal Premchand Ltd (New)', 'India MM BU', 'Salbi'),
  ('Goyal Pulveriser and Chemicals Private Limited', 'SME BU', 'Arathi'),
  ('Basco Products (K) Limited', 'MEA BU', 'Pavan'),
  ('Nigeria Distilleries Limited', 'MEA BU', 'Pavan'),
  ('SPC Healthcare Private Limited', 'SME BU', 'Arathi'),
  ('Remsons Industries Ltd', 'SME BU', 'Arathi'),
  ('Abhishek Distributors Private Limited', 'SME BU', 'Arathi'),
  ('Rolling Pin Gourmet Private Limited', 'SME BU', 'Arathi'),
  ('Nutralife Foods LLP', 'SME BU', 'Arathi'),
  ('MGH Logistics Asia PTE Ltd (Cambodia)', 'India Ent BU', 'Salbi'),
  ('VTC Transport Private Limited', 'SME BU', 'Arathi'),
  ('Glenmark Consumer Care Limited', 'India MM BU', 'Prithee'),
  ('Popup Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Happilo International Private Limited', 'SME BU', 'Arathi'),
  ('Tanvi Fitness Private Limited', 'India Ent BU', 'Pavan'),
  ('Royal Canin India Private Limited', 'India Ent BU', 'Juliya'),
  ('Trivendent Technologies Private Limited ( (Zolopik))', 'Central', NULL),
  ('Angel Touch Hygiene Manufacturing Private Limited', 'SME BU', 'Arathi'),
  ('Foodsolve Private Limited', 'SME BU', 'Arathi'),
  ('Stallion International Pvt. Ltd', 'SME BU', 'Arathi'),
  ('Global Healthfit Retail India Private Limited', 'SME BU', 'Arathi'),
  ('Ekta Cosmetics Limited', 'SME BU', 'Arathi'),
  ('Olam Agri India Private Limited', 'India MM BU', 'Pavan'),
  ('Parivar Healthcare Private Limited', 'SME BU', 'Arathi'),
  ('Ramani Super Grain LLP', 'SME BU', 'Arathi'),
  ('Incredibleindriya Beauty Essentials Private Limited', 'SME BU', 'Arathi'),
  ('Kiri Bottling Company Limited', 'MEA BU', 'Pavan'),
  ('Bluemingo Tech Private Limited', 'India Ent BU', 'Prithee'),
  ('TUV SUD Bangladesh (Pvt.) Ltd.', 'SME BU', 'Arathi'),
  ('Poly Medicure Limited', 'India Ent BU', 'Salbi'),
  ('Johnson & Johnson Private Limited', 'India Ent BU', 'Juliya'),
  ('Sturlite Electric Private Limited', 'India MM BU', 'Pavan'),
  ('Ultratech Cement Limited', 'India Ent BU', 'Prithee'),
  ('SLK Food Specialties Private Limited', 'SME BU', 'Arathi'),
  ('Hatsun Agro Product Limited', 'SME BU', 'Arathi'),
  ('Ellvin Energy Private Limited', 'SME BU', 'Arathi'),
  ('Lagom Labs Private Limited.', 'SME BU', 'Arathi'),
  ('Grand Global Foods Private Limited', 'SME BU', 'Arathi'),
  ('Nutrifoods Ghana Limited', 'MEA BU', 'Pavan'),
  ('Specialty Lubricants Trading (Malaysia) Sdn. Bhd.', 'KAM BU', 'Pavan'),
  ('Denzour Nutrition Private Limited', 'SME BU', 'Arathi'),
  ('Grecy Homeware (India) Private Limited', 'SME BU', 'Arathi'),
  ('Thangam Foods', 'SME BU', 'Arathi'),
  ('YMI Ghar Soaps Private Limited', 'SME BU', 'Arathi'),
  ('Riddhi Siddhi Polymers', 'SME BU', 'Arathi'),
  ('Spectraa Care Private Limited', 'SME BU', 'Arathi'),
  ('J S MASALA CO', 'SME BU', 'Arathi'),
  ('SAMRAT Cement Private Limited', 'India Ent BU', 'Salbi'),
  ('Fava Glocal', 'SME BU', 'Arathi'),
  ('Titan Company Limited', 'India Ent BU', 'Juliya'),
  ('RSS Agrovet', 'SME BU', 'Arathi'),
  ('Mavee Foods Private Limited', 'SME BU', 'Arathi'),
  ('Panella Foods And Beverages Private Limited', 'SME BU', 'Arathi'),
  ('Wuerth India Private Limited', 'India MM BU', 'Prithee'),
  ('Double Yumm Private Limited', 'SME BU', 'Arathi'),
  ('Visalachi Soap Works', 'SME BU', 'Arathi'),
  ('H M SUDHA', NULL, 'Central'),
  ('Bayer Pharmaceuticals Private Limited', 'India Ent BU', 'Prithee'),
  ('Philip Morris Management Services (Middle East) Limited', 'KAM BU', 'Pavan'),
  ('Wacot Limited', 'MEA BU', 'Pavan'),
  ('Durga Enterprises', 'SME BU', 'Arathi'),
  ('Nancy Trading Company', 'India MM BU', 'Salbi'),
  ('August Assortments Private Limited', 'SME BU', 'Arathi'),
  ('Himalayan Distillery Limited', 'India Ent BU', 'Salbi'),
  ('Vietnam Lubricants & Chemicals J/S Company (Vilube Corp)', 'KAM BU', 'Pavan'),
  ('Marmalade Beverages Private Limited', 'SME BU', 'Arathi'),
  ('PZ Wilmar Ltd.', 'MEA BU', 'Pavan'),
  ('Bakers International', 'SME BU', 'Arathi'),
  ('Vloei Private Limited', 'SME BU', 'Arathi'),
  ('La Opala Rg Ltd', 'SME BU', 'Arathi'),
  ('Daily Fresh Fruits India Private Limited', 'India MM BU', 'Juliya'),
  ('Livpure Smart Homes Private Limited', 'India Ent BU', 'Salbi'),
  ('Jagova Consumers Private Limited', 'SME BU', 'Arathi'),
  ('Innoterra Limited', 'SME BU', 'Arathi'),
  ('Marico Limited', 'India Ent BU', 'Prithee'),
  ('Mahesh Namkeen Private Limited', 'India MM North', 'Salbi'),
  ('Trivendent Technologies Private Limited (Zolopik)', NULL, 'Central')
ON CONFLICT (customer_name) DO UPDATE SET
  bu_name = EXCLUDED.bu_name,
  collector_name = EXCLUDED.collector_name,
  updated_at = now();
